use crate::models::{ConfigPlan, ToolEntry, ToolId};
use crate::utils::{diff_preview, ensure_table, new_plan, read_json_object, read_toml};
use aipass_provider_registry::AuthScheme;
use anyhow::Result;
use serde_json::Value;
use std::path::Path;
use toml_edit::{value, Item, Table};

pub fn plan_codex(home: &Path, entry: &ToolEntry) -> Result<(ConfigPlan, String)> {
    let target = home.join(".codex").join("config.toml");
    let mut doc = read_toml(&target)?;
    let provider_name = format!("aipass_{}", crate::utils::slug(&entry.title));
    let mut provider = Table::new();
    provider["name"] = value(entry.title.clone());
    provider["env_key"] = value(entry.env_key.clone());
    if let Some(endpoint) = &entry.endpoint {
        provider["base_url"] = value(endpoint.clone());
    }
    provider["wire_api"] = value(match entry.interface_type {
        aipass_provider_registry::InterfaceType::OpenAiCompatible
        | aipass_provider_registry::InterfaceType::AzureOpenAi => "responses",
        aipass_provider_registry::InterfaceType::AnthropicMessages => "anthropic",
        aipass_provider_registry::InterfaceType::Gemini => "gemini",
        aipass_provider_registry::InterfaceType::Bedrock => "bedrock",
        aipass_provider_registry::InterfaceType::CustomHttp => "custom",
    });
    ensure_table(&mut doc, "model_providers")?[&provider_name] = Item::Table(provider);
    doc["model_provider"] = value(provider_name);
    let content = doc.to_string();
    let plan = new_plan(
        ToolId::Codex,
        target,
        format!("Configure Codex to use {}", entry.title),
        diff_preview(&content),
    );
    Ok((plan, content))
}

pub fn plan_claude_code(home: &Path, entry: &ToolEntry) -> Result<(ConfigPlan, String)> {
    let target = home.join(".claude").join("settings.json");
    let mut json = read_json_object(&target)?;
    json.insert(
        "apiKeyHelper".to_string(),
        Value::String(format!("aipass get {} --field api_key --reveal", entry.id)),
    );
    if let Some(endpoint) = &entry.endpoint {
        json.insert(
            "anthropicBaseUrl".to_string(),
            Value::String(endpoint.clone()),
        );
    }
    let content = serde_json::to_string_pretty(&json)?;
    let plan = new_plan(
        ToolId::ClaudeCode,
        target,
        format!("Configure Claude Code to use {}", entry.title),
        diff_preview(&content),
    );
    Ok((plan, content))
}

pub fn plan_gemini_cli(home: &Path, entry: &ToolEntry) -> Result<(ConfigPlan, String)> {
    let target = home.join(".gemini").join("aipass.env");
    let key = match entry.auth_scheme {
        AuthScheme::GoogleApiKey => "GEMINI_API_KEY",
        _ => &entry.env_key,
    };
    let content = format!(
        "# Generated by AIPass. This file stores helper references, not plaintext secrets.\n{key}=\"$(aipass get {} --field api_key --reveal)\"\n",
        entry.id
    );
    let plan = new_plan(
        ToolId::GeminiCli,
        target,
        format!(
            "Configure Gemini CLI environment helper for {}",
            entry.title
        ),
        diff_preview(&content),
    );
    Ok((plan, content))
}
